name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install PyTorch
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            pip install torch torchvision torchaudio
          else
            pip install torch==2.4.1 torchvision==0.15.1 torchaudio==2.0.1 --extra-index-url https://download.pytorch.org/whl/cu124
          fi

      - name: Install other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4==4.12.3 colorama==0.4.6 diffusers==0.30.3 httpx==0.27.2 nodriver==0.37 pillow==10.4.0 psutil==6.0.0 PyQt6==6.7.1 PyQt6-sip==13.8.0 python-dotenv==1.0.1 sentry-sdk==2.14.0 Nuitka==2.4.8

      - name: Build with Nuitka
        run: |
          nuitka --onefile main.py

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0
          release_name: Release v0.1.0
          body: |
            Binaries for version 0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0
          files: main.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
